# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d008e0d67d4ade1079f89046e4ead689c3b1a8670740a9236523696637fea9dc4b46665a7686b3d6cd69e5ac396d6984017573b088b546fd729844729941c72e

test:
  secret_key_base: edbc1f04fa1e64080ddd2bf1ce63390a090bee049baf7dba9f5db3dcd50ae32fd62f6126d7194216af5e5eea9c064039a5aa365a3d6fbd36bce9a9f69204ee1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
